//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserToDo
    {
        public int Id { get; set; }
        public string ToDoDetail { get; set; }
        public int CreateUserId { get; set; }
        public int ToDoUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsDone { get; set; }
        public Nullable<System.DateTime> DoneDate { get; set; }
        public string DoneDetail { get; set; }
        public bool ActiveFlg { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
    }
}
