//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashTransaction
    {
        public int Id { get; set; }
        public int DealerId { get; set; }
        public int UserId { get; set; }
        public bool IsEntry { get; set; }
        public decimal Price { get; set; }
        public string Detail { get; set; }
        public int SaleId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int DeletedUserId { get; set; }
        public string DeletedReason { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool ActiveFlg { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
    }
}
