//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public int Id { get; set; }
        public int DealerId { get; set; }
        public int CustomerId { get; set; }
        public string OrderNote { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool ActiveFlg { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
