//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbManager : DbContext
    {
        public DbManager()
            : base("name=DbManager")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUserType> AppUserType { get; set; }
        public virtual DbSet<Dealer> Dealer { get; set; }
        public virtual DbSet<DealerAppUser> DealerAppUser { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<ProductTypeSub> ProductTypeSub { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<County> County { get; set; }
        public virtual DbSet<ProductBrand> ProductBrand { get; set; }
        public virtual DbSet<ProductColor> ProductColor { get; set; }
        public virtual DbSet<ProductDetail> ProductDetail { get; set; }
        public virtual DbSet<ProductDocument> ProductDocument { get; set; }
        public virtual DbSet<ProductDocumentType> ProductDocumentType { get; set; }
        public virtual DbSet<ProductFeature> ProductFeature { get; set; }
        public virtual DbSet<ProductFeatureList> ProductFeatureList { get; set; }
        public virtual DbSet<ProductModel> ProductModel { get; set; }
        public virtual DbSet<ProductStatus> ProductStatus { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<TechnicalService> TechnicalService { get; set; }
        public virtual DbSet<TechnicalServiceStatus> TechnicalServiceStatus { get; set; }
        public virtual DbSet<TechnicalServiceHistory> TechnicalServiceHistory { get; set; }
        public virtual DbSet<CashTransaction> CashTransaction { get; set; }
        public virtual DbSet<AppUserToDo> AppUserToDo { get; set; }
        public virtual DbSet<AppUser> AppUser { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerOrder> CustomerOrder { get; set; }
    }
}
