//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int ProductBrandId { get; set; }
        public int ProductModelId { get; set; }
        public int ProductColorId { get; set; }
        public int CustomerIdBuying { get; set; }
        public int CustomerIdSelling { get; set; }
        public string InternalMemoryGB { get; set; }
        public string RamGB { get; set; }
        public string CosmicConditionPercentage { get; set; }
        public string BatteryMah { get; set; }
        public string BatteryPercentage { get; set; }
        public Nullable<System.DateTime> WarrantyEndDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductBrand ProductBrand { get; set; }
        public virtual ProductColor ProductColor { get; set; }
        public virtual ProductModel ProductModel { get; set; }
    }
}
