//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.CashTransaction = new HashSet<CashTransaction>();
        }
    
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int DealerId { get; set; }
        public int CreateUserId { get; set; }
        public int SaleUserId { get; set; }
        public string Name { get; set; }
        public decimal PurchasePriceTL { get; set; }
        public decimal PurchasePriceUSD { get; set; }
        public decimal SellingPriceTL { get; set; }
        public int SaleUnit { get; set; }
        public decimal SalePrice { get; set; }
        public decimal CashPrice { get; set; }
        public decimal CreditCardPrice { get; set; }
        public decimal BankTransferPrice { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int DeletedUserId { get; set; }
        public string DeletedReason { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool ActiveFlg { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual AppUser AppUser2 { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashTransaction> CashTransaction { get; set; }
    }
}
