//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id { get; set; }
        public int DealerId { get; set; }
        public int AppUserId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual DealerAppUser DealerAppUser { get; set; }
    }
}
