//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechnicalService()
        {
            this.TechnicalServiceHistory = new HashSet<TechnicalServiceHistory>();
        }
    
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public int TechnicalServiceStatusId { get; set; }
        public string ProblemDetail { get; set; }
        public string DealerNote { get; set; }
        public string Password { get; set; }
        public string Pattern { get; set; }
        public decimal AstimatedPrice { get; set; }
        public decimal ApprovedPrice { get; set; }
        public decimal CostPrice { get; set; }
        public string TechnicalRepairShop { get; set; }
        public int TechnicalServiceUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool ActiveFlg { get; set; }
        public int DealerId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual TechnicalServiceStatus TechnicalServiceStatus { get; set; }
        public virtual Dealer Dealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechnicalServiceHistory> TechnicalServiceHistory { get; set; }
    }
}
