//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalServiceHistory
    {
        public int Id { get; set; }
        public int TechnicalServiceId { get; set; }
        public int TechnicalServiceStatusId { get; set; }
        public string Detail { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool ActiveFlg { get; set; }
    
        public virtual TechnicalService TechnicalService { get; set; }
        public virtual TechnicalServiceStatus TechnicalServiceStatus { get; set; }
    }
}
